CREATE TABLE IF NOT EXISTS service_types (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(100) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(50) NOT NULL,
  allows_reservation TINYINT(1) NOT NULL DEFAULT 0,
  requires_manual_value TINYINT(1) NOT NULL DEFAULT 0,
  counts_in_financial TINYINT(1) NOT NULL DEFAULT 1,
  shows_in_agenda TINYINT(1) NOT NULL DEFAULT 1,
  accounting_rules JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
