CREATE TABLE IF NOT EXISTS services (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  service_type_id BIGINT UNSIGNED NOT NULL,
  start_at DATETIME NOT NULL,
  duration_hours INT NOT NULL,
  operational_status VARCHAR(50) NOT NULL,
  reservation_expires_at DATETIME NULL,
  performed_at DATETIME NULL,
  notes TEXT NULL,
  financial_status VARCHAR(50) NOT NULL,
  amount_base DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_balance DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_meal DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_transport DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_additional DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  amount_total DECIMAL(12,2) NOT NULL DEFAULT 0,
  payment_due_date DATE NULL,
  payment_at DATETIME NULL,
  version INT NOT NULL DEFAULT 1,
  is_complementary TINYINT(1) NOT NULL DEFAULT 0,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME NULL,
  CONSTRAINT fk_services_user_id FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_services_service_type_id FOREIGN KEY (service_type_id) REFERENCES service_types(id),
  CONSTRAINT fk_services_created_by FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_services_user_start_at (user_id, start_at),
  INDEX idx_services_operational_status (operational_status),
  INDEX idx_services_financial_status (financial_status),
  INDEX idx_services_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
